import { Client, Project, Invoice, Expense, TaxChecklistItem } from './types';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'c-1',
    name: 'Sarah Lin (Studio Lumina)',
    email: 'sarah@lumina-studio.io',
    status: 'Active',
    company: 'Lumina Creative Studio',
    phone: '+1 (415) 555-0182',
    hourlyRate: 125,
    notes: 'Long-term retainer client for full brand and digital design.',
    createdAt: '2026-01-15',
  },
  {
    id: 'c-2',
    name: 'Marcus Vance (FinPulse AI)',
    email: 'm.vance@finpulse.tech',
    status: 'Active',
    company: 'FinPulse Technologies',
    phone: '+1 (212) 555-0941',
    hourlyRate: 150,
    notes: 'Fast-growing fintech startup building automated analytics dashboards.',
    createdAt: '2026-02-01',
  },
  {
    id: 'c-3',
    name: 'Elena Rostova (Nordic Health)',
    email: 'elena@nordichealth.co',
    status: 'Active',
    company: 'Nordic Health Platform',
    phone: '+44 20 7946 0192',
    hourlyRate: 135,
    notes: 'Telehealth mobile app and doctor portal UI design.',
    createdAt: '2026-02-18',
  },
  {
    id: 'c-4',
    name: 'David Chen (AeroLogistics)',
    email: 'dchen@aerologistics.com',
    status: 'Inactive',
    company: 'Aero Freight Global',
    phone: '+1 (312) 555-0377',
    hourlyRate: 110,
    notes: 'Contract concluded last quarter. Good candidate for Q3 re-engagement.',
    createdAt: '2025-10-10',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'p-1',
    client_id: 'c-1',
    title: 'Brand Refresh & Design System v2',
    status: 'In Progress',
    deadline: '2026-10-15',
    budget: 8500,
    description: 'Comprehensive component library, color tokens, and design tokens for web and iOS.',
    progressPercent: 70,
  },
  {
    id: 'p-2',
    client_id: 'c-1',
    title: 'Marketing Landing Page & 3D Assets',
    status: 'Completed',
    deadline: '2026-08-30',
    budget: 4200,
    description: 'High-converting interactive landing page with responsive animations and custom vector graphics.',
    progressPercent: 100,
    completedAt: '2026-08-28',
  },
  {
    id: 'p-3',
    client_id: 'c-2',
    title: 'FinPulse Executive SaaS Dashboard',
    status: 'In Progress',
    deadline: '2026-10-05',
    budget: 9600,
    description: 'Real-time multi-currency trading terminal UI with charts and order books.',
    progressPercent: 45,
  },
  {
    id: 'p-4',
    client_id: 'c-2',
    title: 'Design Audit & Mobile Prototyping',
    status: 'Completed',
    deadline: '2026-07-20',
    budget: 3500,
    description: 'UX teardown and Figma click-through prototype for series A pitch decks.',
    progressPercent: 100,
    completedAt: '2026-07-18',
  },
  {
    id: 'p-5',
    client_id: 'c-3',
    title: 'Patient Scheduling Mobile Flow',
    status: 'Not Started',
    deadline: '2026-11-01',
    budget: 5400,
    description: 'Patient appointment booking, insurance card scanning, and push notification templates.',
    progressPercent: 0,
  },
  {
    id: 'p-6',
    client_id: 'c-4',
    title: 'Fleet Tracking Web Portal',
    status: 'Completed',
    deadline: '2026-03-15',
    budget: 6800,
    description: 'Map visualization for cargo dispatchers with geo-fence alert triggers.',
    progressPercent: 100,
    completedAt: '2026-03-12',
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-1',
    invoice_number: 'INV-2026-001',
    client_id: 'c-1',
    project_id: 'p-2',
    amount: 4200,
    status: 'Paid',
    issue_date: '2026-08-20',
    due_date: '2026-09-03',
    paid_date: '2026-09-01',
    notes: 'Payment received in full via ACH transfer. Thank you!',
  },
  {
    id: 'inv-2',
    invoice_number: 'INV-2026-002',
    client_id: 'c-2',
    project_id: 'p-4',
    amount: 3500,
    status: 'Paid',
    issue_date: '2026-07-22',
    due_date: '2026-08-05',
    paid_date: '2026-08-02',
    notes: 'Paid via Stripe invoice.',
  },
  {
    id: 'inv-3',
    invoice_number: 'INV-2026-003',
    client_id: 'c-4',
    project_id: 'p-6',
    amount: 6800,
    status: 'Paid',
    issue_date: '2026-03-16',
    due_date: '2026-03-30',
    paid_date: '2026-03-29',
    notes: 'Wire transfer received.',
  },
  {
    id: 'inv-4',
    invoice_number: 'INV-2026-004',
    client_id: 'c-1',
    project_id: 'p-1',
    amount: 4250,
    status: 'Paid',
    issue_date: '2026-09-01',
    due_date: '2026-09-15',
    paid_date: '2026-09-14',
    notes: 'Milestone 1 deposit for Design System v2.',
  },
  {
    id: 'inv-5',
    invoice_number: 'INV-2026-005',
    client_id: 'c-2',
    project_id: 'p-3',
    amount: 4800,
    status: 'Sent',
    issue_date: '2026-09-10',
    due_date: '2026-09-24',
    notes: 'Milestone 1 for FinPulse Executive Dashboard.',
  },
  {
    id: 'inv-6',
    invoice_number: 'INV-2026-006',
    client_id: 'c-3',
    project_id: 'p-5',
    amount: 2700,
    status: 'Overdue',
    issue_date: '2026-08-15',
    due_date: '2026-08-29',
    notes: '50% project kickoff retainer. 23 days past due; friendly reminder sent.',
  },
  {
    id: 'inv-7',
    invoice_number: 'INV-2026-007',
    client_id: 'c-1',
    project_id: 'p-1',
    amount: 4250,
    status: 'Draft',
    issue_date: '2026-09-20',
    due_date: '2026-10-04',
    notes: 'Final milestone upon design system completion.',
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    category: 'Software',
    amount: 54,
    date: '2026-09-02',
    description: 'Figma Professional & FigJam Team License',
    isDeductible: true,
    vendor: 'Figma Inc.',
  },
  {
    id: 'exp-2',
    category: 'Software',
    amount: 40,
    date: '2026-09-05',
    description: 'Claude Pro & ChatGPT Plus AI Workflows',
    isDeductible: true,
    vendor: 'Anthropic & OpenAI',
  },
  {
    id: 'exp-3',
    category: 'Software',
    amount: 28,
    date: '2026-09-01',
    description: 'GitHub Copilot & Workspace Cloud Hosting',
    isDeductible: true,
    vendor: 'GitHub & Vercel',
  },
  {
    id: 'exp-4',
    category: 'Internet',
    amount: 95,
    date: '2026-09-03',
    description: 'Gigabit Fiber Business Internet (80% work allocation)',
    isDeductible: true,
    vendor: 'Sonic Fiber',
  },
  {
    id: 'exp-5',
    category: 'Internet',
    amount: 65,
    date: '2026-09-12',
    description: 'Mobile 5G Tethering Hotspot for remote client meetings',
    isDeductible: true,
    vendor: 'T-Mobile Business',
  },
  {
    id: 'exp-6',
    category: 'Advertising',
    amount: 180,
    date: '2026-08-22',
    description: 'Portfolio Promotion & Dribbble Pro Showcase',
    isDeductible: true,
    vendor: 'Dribbble LLC',
  },
  {
    id: 'exp-7',
    category: 'Advertising',
    amount: 125,
    date: '2026-09-08',
    description: 'LinkedIn Creator Boost & Freelance Case Studies',
    isDeductible: true,
    vendor: 'LinkedIn Ads',
  },
  {
    id: 'exp-8',
    category: 'Equipment',
    amount: 799,
    date: '2026-08-10',
    description: 'Dell UltraSharp 32-inch 4K Color-Accurate Monitor',
    isDeductible: true,
    vendor: 'B&H Photo Video',
  },
  {
    id: 'exp-9',
    category: 'Equipment',
    amount: 189,
    date: '2026-07-15',
    description: 'Logitech MX Master 3S & Mechanical Ergonomic Keyboard',
    isDeductible: true,
    vendor: 'Logitech',
  },
  {
    id: 'exp-10',
    category: 'Travel',
    amount: 145,
    date: '2026-08-18',
    description: 'Train & local transport for FinPulse on-site workshop',
    isDeductible: true,
    vendor: 'Amtrak',
  },
  {
    id: 'exp-11',
    category: 'Travel',
    amount: 62,
    date: '2026-09-14',
    description: 'Client Working Lunch with Sarah Lin (50% tax limit)',
    isDeductible: true,
    vendor: 'Blue Bottle & Bistro',
  },
  {
    id: 'exp-12',
    category: 'Other',
    amount: 85,
    date: '2026-09-10',
    description: 'Annual domain renewals & SSL security certificates',
    isDeductible: true,
    vendor: 'Cloudflare Inc.',
  },
];

export const INITIAL_TAX_CHECKLIST: TaxChecklistItem[] = [
  {
    id: 'tax-1',
    title: 'Dedicated Home Office Space',
    category: 'Facilities',
    description: 'Simplified $5/sq ft method (up to 300 sq ft) or actual square footage allocation for utilities and rent.',
    estimatedAnnualDeduction: 1500,
    checked: true,
    tips: 'The space must be used exclusively and regularly as your principal place of business.',
    documentationRequired: 'Floor plan measurement, rental lease or mortgage statement, utility bills.',
  },
  {
    id: 'tax-2',
    title: 'Software & Cloud Subscriptions',
    category: 'Technology',
    description: '100% deductible write-off for SaaS tools used directly in your business (Figma, Adobe, hosting, AI subscriptions).',
    estimatedAnnualDeduction: 1850,
    checked: true,
    tips: 'Keep monthly digital receipts; credit card statements alone are often insufficient during audits.',
    documentationRequired: 'Itemized invoice receipts showing software vendor name and date.',
  },
  {
    id: 'tax-3',
    title: 'Business Phone & Internet Services',
    category: 'Utilities',
    description: 'Portion of high-speed internet and mobile phone bill allocated strictly for professional freelance work.',
    estimatedAnnualDeduction: 1200,
    checked: true,
    tips: 'Usually 50% to 80% allocation is defensible if you work predominantly from home.',
    documentationRequired: 'Monthly utility invoices with explicit work allocation logs.',
  },
  {
    id: 'tax-4',
    title: 'Equipment Depreciation (Section 179)',
    category: 'Hardware',
    description: 'Laptops, monitors, cameras, tablets, and office furniture can be fully expensed in the year of purchase.',
    estimatedAnnualDeduction: 3200,
    checked: true,
    tips: 'Section 179 allows 100% first-year expensing rather than multi-year straight-line depreciation.',
    documentationRequired: 'Purchase receipts with serial numbers and proof of purchase date.',
  },
  {
    id: 'tax-5',
    title: 'Professional Development & Courses',
    category: 'Education',
    description: 'Online technical courses, UX workshops, books, and industry conferences that maintain or improve skills.',
    estimatedAnnualDeduction: 650,
    checked: false,
    tips: 'Must maintain or improve current freelance trade skills; cannot qualify you for an entirely new profession.',
    documentationRequired: 'Course certificates, syllabus outline, and payment confirmation.',
  },
  {
    id: 'tax-6',
    title: 'Freelance Health Insurance Premiums',
    category: 'Health',
    description: 'Self-employed health insurance deduction taken directly as an adjustment to gross income.',
    estimatedAnnualDeduction: 4800,
    checked: false,
    tips: 'Available if you are not eligible to participate in an employer-sponsored plan (including through a spouse).',
    documentationRequired: 'Form 1095-A / premium statements from your health insurance carrier.',
  },
  {
    id: 'tax-7',
    title: 'Business Travel & Client Meals',
    category: 'Travel & Meals',
    description: 'Travel expenses (flights, trains, lodging) are 100% deductible; business meals with clients are 50% deductible.',
    estimatedAnnualDeduction: 850,
    checked: true,
    tips: 'Always jot down the business purpose and client attendee names on the back of receipt photos.',
    documentationRequired: 'Itemized meal/transit receipts with business agenda noted.',
  },
  {
    id: 'tax-8',
    title: 'Banking, Payment Processing & Legal Fees',
    category: 'Financial Services',
    description: 'Stripe transaction fees (2.9% + 30¢), wire transfer costs, CPA accounting advice, and LLC state fees.',
    estimatedAnnualDeduction: 920,
    checked: false,
    tips: 'Export your annual Stripe/PayPal fee summary report at the close of every tax year.',
    documentationRequired: 'Year-end payment gateway transaction fee statements.',
  },
];
